---
title: "R Notebook"
output: html_notebook
---

```{r}
library(DESeq2)
Counts <- read.delim("count_table.csv", header = TRUE, row.names = 1, sep = ",")
Counts <- Counts[which(rowSums(Counts) > 0),]
condition <- factor(c("C","C","C","C", "S","S","S","S"))
coldata <- data.frame(row.names = colnames(Counts), condition)
dds <- DESeqDataSetFromMatrix(countData = Counts, colData = coldata, design = ~condition)
dds <- DESeq(dds)
res <- results(dds, contrast = c("condition", "S", "C"))
res <- na.omit(res)
res <- res[res$baseMean > 50,]
```

```{r}
res
```


```{r}
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("org.Hs.eg.db") #org.Mm.eg.db for mouse


if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("clusterProfiler")


if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("AnnotationDbi")
```


```{r}
library(org.Hs.eg.db)
library(clusterProfiler)
```




```{r}
res <- res[order(-res$stat),]
res
```

```{r}
gene_list <- res$stat
names(gene_list) <- rownames(res)
gene_list
```



```{r}
gse <- gseGO(gene_list,
             ont = "BP",
             keyType = "ENSEMBL",
             OrgDb = "org.Hs.eg.db",
             eps = 1e-300)
```

```{r}
as.data.frame(gse)
```


```{r}
fit <- gseaplot(gse, geneSetID = 1)

png("gsea.png", res = 250, width = 2000, height = 1300)
print(fit)
dev.off()

fit
```


















































