---
title: "R Notebook"
output: html_notebook
---

```{r}
if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("SingleR")
```
```{r}
install.packages('Seurat')
```

```{r}
#very basic Seurat preprocessing
prep_data <- function(Data.path){
  Raw_data <- Read10X(data.dir = Data.path)
  seuset_data <- CreateSeuratObject(counts = Raw_data, min.cells = 3, min.features = 200)
  seuset_data[["percent.mt"]] <- PercentageFeatureSet(seuset_data, pattern = "mt-")
  lb <- quantile(seuset_data[["nFeature_RNA"]]$nFeature_RNA, probs = 0.01)
  ub <- quantile(seuset_data[["nFeature_RNA"]]$nFeature_RNA, probs = 0.99)
  seuset_data <- seuset_data[, seuset_data[["nFeature_RNA"]] > lb & seuset_data[["nFeature_RNA"]] < ub & seuset_data[["percent.mt"]] < 15] 
  seuset_data <- NormalizeData(object = seuset_data, verbose = FALSE)
  seuset_data <- FindVariableFeatures(object = seuset_data, nfeatures = 3000, verbose = FALSE, selection.method = 'vst')
  seuset_data <- ScaleData(seuset_data, verbose = FALSE)
  seuset_data <- RunPCA(seuset_data, npcs = 20, verbose = FALSE)
  seuset_data <- FindNeighbors(seuset_data, dims = 1:20)
  seuset_data <- FindClusters(seuset_data, resolution = 0.3)
  seuset_data <- RunUMAP(seuset_data, reduction = "pca", dims = 1:20)
  return(seuset_data)
}
```


```{r}
data <- prep_data("Lung1/outs/filtered_feature_bc_matrix")
```
```{r}
a <- DimPlot(data, reduction = "umap", label=TRUE)

png("./umap_u.png", res = 250, width = 1500, height = 1500)

print(a)
dev.off()
#a + b + c
a
```

```{r}
library(SingleR)
```

```{r}
ref <- celldex::MouseRNAseqData()
```

```{r}
results <- SingleR(test = as.SingleCellExperiment(data), ref = ref, labels = ref$label.main)
```

```{r}
data$singlr_labels <- results$labels
```

```{r}
DimPlot(data, reduction = 'umap', group.by = 'singlr_labels', label = TRUE)
```

```{r}
FeaturePlot(data, features = c("Ptprc", "Cd3e"))
```

```{r}
if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("scRNAseq")
```
```{r}
if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("scuttle")
```
```{r}
if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("TabulaMurisData")
```
```{r}
library(ExperimentHub)
```
```{r}
eh <- ExperimentHub()
```
```{r}
query(eh, "TabulaMurisData")
```
```{r}
eh[['EH1617']]
```

```{r}
lung_ref <- eh[['EH1617']]
lung_ref <- lung_ref[,lung_ref$tissue == 'Lung']
lung_ref <- lung_ref[,!is.na(lung_ref$cell_ontology_class)]
```

```{r}
lung_ref
```

```{r}
library(scuttle)
```

```{r}
lung_ref <- logNormCounts(lung_ref)
```


```{r}
results <- SingleR(test = as.SingleCellExperiment(data), ref = lung_ref, labels = lung_ref$cell_ontology_class)
```


```{r}
data$singlr_label <- results$labels
```

```{r}
a <- DimPlot(data, reduction = "umap", group.by = 'singlr_label', label = FALSE)

png("./umap_l.png", res = 250, width = 2500, height = 1500)

print(a)
dev.off()
#a + b + c
a
```

















